apiVersion: v1
kind: Service
metadata:
  name: django-cluster-ip-service
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8010
      nodePort: 31000