
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  namespace: default
spec:
  rules:
  - host: ejedzenie.com
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: django-cluster-ip-service
              port:
                number: 8010